### ISSUE TITLE
when collocating the cpe and ice then the ports should be mapped differently

### ISSUE THREAD

**Issue by DominikBaer** [ibm-ecm/container-icn#2]
docker run -d --name icn -p **9081**:9080 -p **9445**:9443 -e ICNSCHEMA=ICNSCHEMA -v /home/data/plugins:/opt/ibm/plugins -v /home/data/viewerlog:/opt/ibm/viewerconfig/logs -v /home/data/viewercache:/opt/ibm/viewerconfig/cache -v /home/data/logs:/opt/ibm/wlp/usr/servers/defaultServer/logs -v /home/data/configDropins/overrides:/opt/ibm/wlp/usr/servers/defaultServer/configDropins/overrides ibmcorp/ecm_earlyadopters_icn:earlyadopters-gm5.5

**Comment by lianxj-ibm** [comment]
This is just a sample and you can modify the port accordingly in real deployment environment.
