### ISSUE TITLE
Connectivity for ICN / P8 would be handy to include in documentation

### ISSUE THREAD

**Issue by DominikBaer** [ibm-ecm/container-icn#4]
http//CPEDockerHost:9080/wsi/FNCEWS40MTOM/

**Comment by lianxj-ibm** [comment]
Thanks for the suggestion. This is a topic regarding content navigator administration, we will suggest to add the content to the navigator knowledge center. 
https://www.ibm.com/support/knowledgecenter/SSEUEX_3.0.3/KC_ditamaps/contentnavigator.htm
